from . import crm_lead
from . import project_request_reject_wizard
from . import crm_client_segment
from . import crm_project_type
from . import crm_project_feature
from . import project_assignment_team
from . import project_team_assignment
from . import project_team_assignment_wizard
from . import hr_employee
from . import crm_email_log
from . import res_config_settings