"""CRM Lead extensions for project-request workflow.

This file adds:
- Project request workflow fields (technical review, proposal, approvals)
- Follow-up tracking fields (used by dashboard + cron reminders)
- Convenience compute helpers for UI buttons/roles
- Optional PDF->summary generation using OpenAI
"""

import base64
import re
from datetime import timedelta
from io import BytesIO

import requests

from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError


class CrmLead(models.Model):
    """Extend `crm.lead` with a guided project-request flow."""

    _inherit = 'crm.lead'

    # Technical review inputs set by technical reviewers.
    technical_feasibility = fields.Selection([
        ('pending', 'Pending'),
        ('feasible', 'Feasible'),
        ('not_feasible', 'Not Feasible'),
    ], string="Technical Feasibility Status", default='pending', tracking=True)

    complexity_level = fields.Selection([
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ], string="Complexity Level", tracking=True)

    # Planning / proposal information captured during the flow.
    estimated_duration = fields.Char(string="Estimated Delivery Duration", tracking=True)
    project_deadline = fields.Date(string="Project Deadline", tracking=True)
    proposal_summary = fields.Text(string="Proposal Summary", tracking=True)
    proposal_amount = fields.Float(string="Estimated Project Value", tracking=True)
    negotiation_notes = fields.Text(string="Negotiation Notes", tracking=True)
    rejection_reason = fields.Text(string="Rejection Reason", tracking=True)

    # Approval state is separate from stage to support more explicit logic + auditing.
    approval_state = fields.Selection([
        ('not_needed', 'Not Needed'),
        ('to_approve', 'To Approve'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ], string="Approval State", default='not_needed', tracking=True)

    approved_by = fields.Many2one(
        'res.users',
        string="Approved By",
        readonly=True,
        tracking=True,
    )

    approved_on = fields.Datetime(
        string="Approved On",
        readonly=True,
        tracking=True,
    )

    rejected_by = fields.Many2one(
        'res.users',
        string="Rejected By",
        readonly=True,
        tracking=True,
    )

    rejected_on = fields.Datetime(
        string="Rejected On",
        readonly=True,
        tracking=True,
    )

    # Follow-up tracking (these fields are also used by dashboard KPIs).
    last_followup_date = fields.Date(string="Last Follow-up Date", tracking=True)
    next_followup_date = fields.Date(string="Next Follow-up Date", tracking=True)

    followup_status = fields.Selection([
        ('not_started', 'Not Started'),
        ('ongoing', 'Ongoing'),
        ('done', 'Done'),
        ('overdue', 'Overdue'),
    ], string="Follow-up Status", default='not_started', tracking=True)

    # Flag toggled by the cron when follow-up becomes overdue.
    inactive_alert = fields.Boolean(string="Needs Follow-up", default=False, tracking=True)

    # Proposal PDF fields
    proposal_pdf = fields.Binary(string="Proposal PDF", attachment=True)
    proposal_pdf_filename = fields.Char(string="Proposal PDF Filename")
    proposal_pdf_processed_by = fields.Many2one(
        'res.users',
        string="Summary Generated By",
        readonly=True,
        tracking=True,
    )
    proposal_pdf_processed_on = fields.Datetime(
        string="Summary Generated On",
        readonly=True,
        tracking=True,
    )

    # Stage helpers
    is_stage_new_inquiry = fields.Boolean(compute="_compute_stage_flags", store=True)
    is_stage_initial_discussion = fields.Boolean(compute="_compute_stage_flags", store=True)
    is_stage_analysis = fields.Boolean(compute="_compute_stage_flags", store=True)
    is_stage_solution_design = fields.Boolean(compute="_compute_stage_flags", store=True)
    is_stage_proposal = fields.Boolean(compute="_compute_stage_flags", store=True)
    is_stage_waiting_approval = fields.Boolean(compute="_compute_stage_flags", store=True)
    is_stage_approved = fields.Boolean(compute="_compute_stage_flags", store=True)
    is_stage_rejected = fields.Boolean(compute="_compute_stage_flags", store=True)

    # Button visibility helpers
    show_start_analysis_btn = fields.Boolean(compute="_compute_action_buttons", store=True)
    show_submit_proposal_btn = fields.Boolean(compute="_compute_action_buttons", store=True)
    show_send_to_approval_btn = fields.Boolean(compute="_compute_action_buttons", store=True)
    show_approve_btn = fields.Boolean(compute="_compute_action_buttons", store=True)
    show_reject_btn = fields.Boolean(compute="_compute_action_buttons", store=True)

    # Role helpers
    can_edit_technical_fields = fields.Boolean(compute="_compute_can_edit_technical_fields")
    can_edit_proposal_fields = fields.Boolean(compute="_compute_can_edit_proposal_fields")
    can_use_flow_buttons = fields.Boolean(compute="_compute_can_use_flow_buttons")

    @api.model_create_multi
    def create(self, vals_list):
        """Create leads and schedule an initial follow-up activity."""
        records = super().create(vals_list)
        for record in records:
            record._create_followup_activity(
                summary="Initial Follow-up",
                note="A new project request was created. Please review and follow up."
            )
        return records

    @api.depends('stage_id', 'stage_id.name')
    def _compute_stage_flags(self):
        """Expose stage booleans for clean view logic."""
        for record in self:
            stage_name = (record.stage_id.name or '').strip()

            record.is_stage_new_inquiry = stage_name == 'New Inquiry'
            record.is_stage_initial_discussion = stage_name == 'Initial Discussion'
            record.is_stage_analysis = stage_name == 'Requirement Analysis'
            record.is_stage_solution_design = stage_name == 'Solution Design'
            record.is_stage_proposal = stage_name == 'Proposal Submitted'
            record.is_stage_waiting_approval = stage_name == 'Waiting Approval'
            record.is_stage_approved = stage_name == 'Approved'
            record.is_stage_rejected = stage_name == 'Rejected'

    @api.depends('stage_id', 'stage_id.name')
    def _compute_action_buttons(self):
        """Compute visibility of flow buttons based on stage."""
        for record in self:
            stage_name = (record.stage_id.name or '').strip()

            record.show_start_analysis_btn = stage_name in ['New Inquiry', 'Initial Discussion']
            record.show_submit_proposal_btn = stage_name in ['Requirement Analysis', 'Solution Design']
            record.show_send_to_approval_btn = stage_name == 'Proposal Submitted'
            record.show_approve_btn = stage_name == 'Waiting Approval'
            record.show_reject_btn = stage_name == 'Waiting Approval'

    def _compute_can_edit_technical_fields(self):
        """Role check: who can edit technical feasibility fields."""
        user = self.env.user
        can_edit = (
            user.has_group('crm_workflow_custom.group_crm_technical_reviewer') or
            user.has_group('crm_workflow_custom.group_crm_workflow_manager')
        )
        for record in self:
            record.can_edit_technical_fields = can_edit

    def _compute_can_edit_proposal_fields(self):
        """Role check: who can edit proposal + planning fields."""
        user = self.env.user
        is_manager = user.has_group('crm_workflow_custom.group_crm_workflow_manager')
        is_reviewer = user.has_group('crm_workflow_custom.group_crm_technical_reviewer')
        is_workflow_user = user.has_group('crm_workflow_custom.group_crm_workflow_user')

        for record in self:
            record.can_edit_proposal_fields = is_manager or (is_workflow_user and not is_reviewer)

    def _compute_can_use_flow_buttons(self):
        """Role check: who can use workflow transition buttons."""
        user = self.env.user
        is_manager = user.has_group('crm_workflow_custom.group_crm_workflow_manager')
        is_reviewer = user.has_group('crm_workflow_custom.group_crm_technical_reviewer')
        is_workflow_user = user.has_group('crm_workflow_custom.group_crm_workflow_user')

        for record in self:
            record.can_use_flow_buttons = is_manager or (is_workflow_user and not is_reviewer)

    @api.onchange('complexity_level')
    def _onchange_complexity_level_auto_fill_planning(self):
        """Suggest duration/deadline defaults from the selected complexity."""
        duration_map = {
            'low': 30,
            'medium': 90,
            'high': 180,
        }

        for record in self:
            if not record.complexity_level:
                continue

            suggested_days = duration_map.get(record.complexity_level)
            if not suggested_days:
                continue

            if not record.estimated_duration:
                record.estimated_duration = f"{suggested_days} days"

            if not record.project_deadline:
                record.project_deadline = fields.Date.today() + timedelta(days=suggested_days)

    @api.constrains('partner_id', 'type')
    def _check_internal_contact_required(self):
        """Enforce a contact for non-lead types."""
        for record in self:
            if record.type != 'lead' and not record.partner_id:
                raise ValidationError(_("Contact is required."))

    @api.constrains('estimated_duration')
    def _check_estimated_duration_value(self):
        """Basic validation to avoid negative/zero durations."""
        for record in self:
            value = (record.estimated_duration or '').strip()
            if not value:
                continue

            if value.startswith('-'):
                raise ValidationError(_("Estimated Delivery Duration cannot be negative."))

            number_match = re.match(r'^(-?\d+(?:\.\d+)?)', value)
            if number_match:
                numeric_value = float(number_match.group(1))
                if numeric_value <= 0:
                    raise ValidationError(_("Estimated Delivery Duration must be greater than 0."))

    @api.constrains('proposal_amount')
    def _check_proposal_amount_value(self):
        """Prevent invalid (<= 0) project values."""
        for record in self:
            if record.proposal_amount and record.proposal_amount <= 0:
                raise ValidationError(_("Estimated Project Value must be greater than 0."))

    def _get_stage_by_name(self, stage_name):
        """Fetch a `crm.stage` by exact name (raises if missing)."""
        stage = self.env['crm.stage'].search([('name', '=', stage_name)], limit=1)
        if not stage:
            raise UserError(_("Stage '%s' was not found.") % stage_name)
        return stage

    def _create_followup_activity(self, summary, note=''):
        """Create a TODO activity for the assigned salesperson (if any)."""
        activity_type = self.env.ref('mail.mail_activity_data_todo', raise_if_not_found=False)
        if not activity_type:
            return

        model_id = self.env['ir.model']._get_id('crm.lead')

        for record in self:
            if not record.user_id:
                continue

            self.env['mail.activity'].create({
                'activity_type_id': activity_type.id,
                'summary': summary,
                'note': note,
                'res_model_id': model_id,
                'res_id': record.id,
                'user_id': record.user_id.id,
                'date_deadline': fields.Date.today(),
            })

    def _extract_text_from_uploaded_pdf(self):
        """Read up to ~20 pages of text from the uploaded proposal PDF."""
        self.ensure_one()

        if not self.proposal_pdf:
            raise UserError(_("Please upload a proposal PDF first."))

        filename = (self.proposal_pdf_filename or '').strip()
        if not filename:
            raise UserError(_("Please upload a valid PDF file."))

        if not filename.lower().endswith('.pdf'):
            raise UserError(_("Only PDF files are allowed."))

        try:
            from pypdf import PdfReader
        except Exception:
            raise UserError(_("The server package 'pypdf' is required for this feature."))

        try:
            pdf_bytes = base64.b64decode(self.proposal_pdf)
            reader = PdfReader(BytesIO(pdf_bytes))

            extracted_parts = []
            for page in reader.pages[:20]:
                text = page.extract_text() or ""
                text = text.strip()
                if text:
                    extracted_parts.append(text)

            extracted_text = "\n\n".join(extracted_parts).strip()
        except Exception as exc:
            raise UserError(_("Could not read the uploaded PDF: %s") % str(exc))

        if not extracted_text:
            raise UserError(_(
                "No readable text was found in the uploaded PDF. "
                "Please upload a text-based PDF, not a scanned image PDF."
            ))

        if len(extracted_text) > 20000:
            extracted_text = extracted_text[:20000]

        return extracted_text

    def _extract_summary_from_responses_payload(self, payload):
        """Normalize different response formats into a single text summary."""
        if payload.get("output_text"):
            return payload.get("output_text", "").strip()

        output_items = payload.get("output", []) or []
        collected = []

        for item in output_items:
            if item.get("type") != "message":
                continue
            for content in item.get("content", []) or []:
                content_type = content.get("type")
                if content_type in ("output_text", "text"):
                    text = content.get("text", "")
                    if text:
                        collected.append(text)

        return "\n".join(collected).strip()

    def _call_openai_summary_api(self, source_text):
        """Call OpenAI Responses API to summarize the PDF text."""
        self.ensure_one()

        config = self.env['ir.config_parameter'].sudo()
        api_key = config.get_param('openai_api_key')
        model = config.get_param('openai_model')

        if not api_key:
            raise UserError(_("Missing system parameter: openai_api_key"))
        if not model:
            raise UserError(_("Missing system parameter: openai_model"))

        prompt = (
            "Summarize the following project proposal document into one concise professional paragraph "
            "for the Proposal Summary field in an ERP/CRM system.\n\n"
            "Requirements:\n"
            "- Maximum 120 words.\n"
            "- Focus on project objective, key scope, expected solution, main deliverables, and important business context.\n"
            "- Do not use bullet points.\n"
            "- Do not copy long sentences directly from the document.\n"
            "- Return plain text only.\n\n"
            "Document text:\n"
            f"{source_text}"
        )

        payload = {
            "model": model,
            "input": [
                {
                    "role": "system",
                    "content": [
                        {
                            "type": "input_text",
                            "text": (
                                "You summarize business project proposal documents for CRM proposal records. "
                                "Write one concise professional paragraph only. "
                                "Do not copy large sections of the source text."
                            ),
                        }
                    ],
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": prompt,
                        }
                    ],
                },
            ],
            "text": {
                "format": {
                    "type": "text"
                }
            },
            "temperature": 0.2,
        }

        try:
            response = requests.post(
                "https://api.openai.com/v1/responses",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=120,
            )
            response.raise_for_status()
            data = response.json()
        except requests.exceptions.RequestException as exc:
            raise UserError(_("OpenAI request failed: %s") % str(exc))

        summary_text = self._extract_summary_from_responses_payload(data)
        if not summary_text:
            raise UserError(_("The AI service returned an empty summary."))

        return summary_text.strip()

    def action_generate_summary_from_pdf(self):
        """Button action: generate and store `proposal_summary` from `proposal_pdf`."""
        for record in self:
            extracted_text = record._extract_text_from_uploaded_pdf()
            summary_text = record._call_openai_summary_api(extracted_text)

            record.proposal_summary = summary_text
            record.proposal_pdf_processed_by = self.env.user
            record.proposal_pdf_processed_on = fields.Datetime.now()

        return {
            "type": "ir.actions.client",
            "tag": "reload",
        }

    def _get_proposal_validation_errors(self):
        """Return a list of missing/invalid fields required to proceed."""
        self.ensure_one()
        errors = []

        if self.type != 'lead' and not self.partner_id:
            errors.append(_("Contact is required."))

        if not self.technical_feasibility or self.technical_feasibility == 'pending':
            errors.append(_("Technical Feasibility Status must be set."))

        if self.technical_feasibility == 'not_feasible':
            errors.append(_("This request cannot move forward because Technical Feasibility Status is set to Not Feasible."))

        if not self.complexity_level:
            errors.append(_("Complexity Level is required."))

        if not self.estimated_duration:
            errors.append(_("Estimated Delivery Duration is required."))
        else:
            value = (self.estimated_duration or '').strip()
            if value.startswith('-'):
                errors.append(_("Estimated Delivery Duration cannot be negative."))
            else:
                number_match = re.match(r'^(-?\d+(?:\.\d+)?)', value)
                if number_match:
                    numeric_value = float(number_match.group(1))
                    if numeric_value <= 0:
                        errors.append(_("Estimated Delivery Duration must be greater than 0."))

        if not self.project_deadline:
            errors.append(_("Project Deadline is required."))

        if not self.proposal_summary:
            errors.append(_("Proposal Summary is required."))

        if not self.proposal_amount:
            errors.append(_("Estimated Project Value is required."))
        elif self.proposal_amount <= 0:
            errors.append(_("Estimated Project Value must be greater than 0."))

        return errors

    def _raise_combined_validation_error(self, errors, action_label):
        """Raise one friendly error message containing all validation issues."""
        if errors:
            message = _("Please complete the following before %s:\n- %s") % (
                action_label,
                "\n- ".join(errors)
            )
            raise ValidationError(message)

    @api.model
    def sync_workflow_stages(self):
        """Create/update the project-request stages and migrate old stages."""
        stage_model = self.env['crm.stage'].sudo()
        lead_model = self.env['crm.lead'].sudo()

        desired_stages = [
            {'name': 'New Inquiry', 'sequence': 1, 'is_won': False, 'fold': False},
            {'name': 'Initial Discussion', 'sequence': 2, 'is_won': False, 'fold': False},
            {'name': 'Requirement Analysis', 'sequence': 3, 'is_won': False, 'fold': False},
            {'name': 'Solution Design', 'sequence': 4, 'is_won': False, 'fold': False},
            {'name': 'Proposal Submitted', 'sequence': 5, 'is_won': False, 'fold': False},
            {'name': 'Waiting Approval', 'sequence': 6, 'is_won': False, 'fold': False},
            {'name': 'Approved', 'sequence': 7, 'is_won': True, 'fold': False},
            {'name': 'Rejected', 'sequence': 8, 'is_won': False, 'fold': False},
        ]

        created_or_existing = {}
        for vals in desired_stages:
            stage = stage_model.search([('name', '=', vals['name'])], limit=1)
            if stage:
                stage.write({
                    'sequence': vals['sequence'],
                    'is_won': vals['is_won'],
                    'fold': vals['fold'],
                })
            else:
                stage = stage_model.create({
                    'name': vals['name'],
                    'sequence': vals['sequence'],
                    'is_won': vals['is_won'],
                    'fold': vals['fold'],
                })
            created_or_existing[vals['name']] = stage

        stage_mapping = {
            'New': 'New Inquiry',
            'Qualified': 'Initial Discussion',
            'Proposition': 'Proposal Submitted',
            'Won': 'Approved',
            'Lost': 'Rejected',
        }

        for old_name, new_name in stage_mapping.items():
            old_stage = stage_model.search([('name', '=', old_name)], limit=1)
            new_stage = created_or_existing.get(new_name)
            if old_stage and new_stage and old_stage.id != new_stage.id:
                leads = lead_model.search([('stage_id', '=', old_stage.id)])
                if leads:
                    leads.write({'stage_id': new_stage.id})

        return True

    def action_start_analysis(self):
        """Move lead to 'Requirement Analysis' and start follow-up tracking."""
        for record in self:
            stage = record._get_stage_by_name('Requirement Analysis')
            record.stage_id = stage.id
            record.followup_status = 'ongoing'
            record.last_followup_date = fields.Date.today()

            record._create_followup_activity(
                summary="Technical Analysis Required",
                note="Please review the project requirements and update the technical evaluation."
            )

    def action_submit_proposal(self):
        """Move to 'Proposal Submitted' after validating proposal fields."""
        for record in self:
            errors = record._get_proposal_validation_errors()
            record._raise_combined_validation_error(errors, _("submitting the proposal"))

            stage = record._get_stage_by_name('Proposal Submitted')
            record.stage_id = stage.id
            record.approval_state = 'to_approve'
            record.followup_status = 'ongoing'
            record.last_followup_date = fields.Date.today()

            record._create_followup_activity(
                summary="Proposal Follow-up",
                note="The proposal has been submitted. Follow up with the client or internal team as needed."
            )

    def action_send_to_approval(self):
        """Move to 'Waiting Approval' (keeps audit fields in approval_state)."""
        for record in self:
            errors = record._get_proposal_validation_errors()
            record._raise_combined_validation_error(errors, _("sending for approval"))

            stage = record._get_stage_by_name('Waiting Approval')
            record.stage_id = stage.id
            record.approval_state = 'to_approve'
            record.last_followup_date = fields.Date.today()

            record._create_followup_activity(
                summary="Approval Needed",
                note="This project request is waiting for approval."
            )

    def action_approve_project(self):
        """Approve: move stage, set approval audit fields, stop follow-ups."""
        for record in self:
            stage = record._get_stage_by_name('Approved')
            record.stage_id = stage.id
            record.approval_state = 'approved'
            record.approved_by = self.env.user
            record.approved_on = fields.Datetime.now()
            record.followup_status = 'done'
            record.last_followup_date = fields.Date.today()
            record.inactive_alert = False

    def action_reject_project(self):
        """Open a wizard to collect rejection reason."""
        self.ensure_one()

        return {
            'type': 'ir.actions.act_window',
            'name': _('Reject Project'),
            'res_model': 'crm.reject.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_lead_id': self.id,
                'default_rejection_reason': self.rejection_reason or '',
            },
        }

    def action_reject_project_confirm(self):
        """Reject: requires a reason, then updates audit fields and ends follow-up."""
        for record in self:
            if not record.rejection_reason:
                raise ValidationError(_("Please enter the rejection reason before rejecting the project."))

            stage = record._get_stage_by_name('Rejected')
            record.stage_id = stage.id
            record.approval_state = 'rejected'
            record.rejected_by = self.env.user
            record.rejected_on = fields.Datetime.now()
            record.followup_status = 'done'
            record.last_followup_date = fields.Date.today()
            record.inactive_alert = False

    @api.model
    def _cron_check_inactive_leads(self):
        """Cron: mark overdue follow-ups and create a reminder activity."""
        today = fields.Date.today()

        leads = self.search([
            ('next_followup_date', '!=', False),
            ('next_followup_date', '<', today),
            ('approval_state', 'not in', ['approved', 'rejected']),
        ])

        activity_type = self.env.ref('mail.mail_activity_data_todo', raise_if_not_found=False)
        model_id = self.env['ir.model']._get_id('crm.lead')

        for lead in leads:
            lead.followup_status = 'overdue'
            lead.inactive_alert = True

            if activity_type and lead.user_id:
                existing_activity = self.env['mail.activity'].search([
                    ('res_model_id', '=', model_id),
                    ('res_id', '=', lead.id),
                    ('activity_type_id', '=', activity_type.id),
                    ('summary', '=', 'Overdue Follow-up Reminder'),
                    ('user_id', '=', lead.user_id.id),
                ], limit=1)

                if not existing_activity:
                    self.env['mail.activity'].create({
                        'activity_type_id': activity_type.id,
                        'summary': 'Overdue Follow-up Reminder',
                        'note': 'This project request has passed its next follow-up date and needs attention.',
                        'res_model_id': model_id,
                        'res_id': lead.id,
                        'user_id': lead.user_id.id,
                        'date_deadline': today,
                    })